### ISSUE TITLE
what's the basic technology of ekho?

### ISSUE THREAD

**Issue by dongfangyixi** [hgneng/ekho#1]
hi, i'm really interested in this project. 
one thing i'm curious about is the basic theory of ekho. is it unit selection, hmm, or deep learning technologies?

**Comment by hgneng** [comment]
The theory of Ekho is simpler than you thought. It just records each pinyin's wave and join them together.

**Comment by hgneng** [comment]
Here is a document although it's somewhat of outdated.
http://www.eguidedog.net/doc/doc_develop_ekho.php

**Comment by hgneng** [comment]
I think it belongs to "unit selection".
