### ISSUE TITLE
请教 关于ekho的Java调用

### ISSUE THREAD

**Issue by yuanxuzhang** [hgneng/ekho#10]
你好 余音大神，想请教下：
1. ekho能不能封装成JAVA的类库（或者为Java程序提供API接口也可以）。
2. 还有就是 我下载Windows (32bit, SAPI5): ekho-6.5.exe (37M) 安装在win7 64 后报 “
Error initializing TTSApp. Shutting down.“ 
请不吝赐教。

**Comment by hgneng** [comment]
你可能直接搜一下Java怎样调用SAPI5接口会是比较正确的方向。
我在Win7 64虚拟机里并没有重现问题，我略怀疑你安装的路径可能有权限问题，不确定，这些年很少使用Windows了。

**Comment by yuanxuzhang** [comment]
多谢。
1. Error initializing TTSApp. Shutting down.的问题是我自己电脑系统的问题，打上补丁就可以了。
2. 多谢给了这个方向的解决方案  SAPI5。
3. 在下边的方案中，我看到有Android: export Java API for Android的接口，没有android开发经验，所以想请教下：这样的情况下普通的Java程序能访问这个Java API吗？
 +----------------+
| Web TTS Client |
+----------------+-------+------------------+---------------+---------+
| Web TTS Server | SAPI5 |     OpenTTS/     | Command Line/ | Android |
|                |       | SpeechDispatcher |      Gtk+     |         |
+----------------+-------+------------------+---------------+---------+
|                                Ekho Library                         |
+----------+------------+------------+---------+--------+-------------+
|   Dict   |  Festival  | SoundTouch | Sndfile |  Lame  | Pulseaudio  |
+----------+------------+      /     +---------+    /   +-------------+
|  utfcpp  | sr-convert |    Sonic   |   GSM   | Vorbis |
+----------+------------+------------+---------+--------+

**Comment by hgneng** [comment]
Android的API是Android专用的，并且没有维护了，因为Android上有更好的免费中文TTS，我觉得没有维护的必要。PC上的Java调用不了Android专用的API。

**Comment by yuanxuzhang** [comment]
window下SAPI5方式基本可以满足需求，非常感谢。
