### ISSUE TITLE
是否可以移植windows 下的tts语音库至linux下呢？

### ISSUE THREAD

**Issue by 172721404** [hgneng/ekho#11]
碧如说 讯飞的语音库  还有一些很优秀的语音库？
是否可以移植到Linux  并且用ekho读出来呢？

**Comment by hgneng** [comment]
讯飞本身有Linux版本。这个主要是版权问题。

**Comment by 172721404** [comment]
具体怎么实现呢？找了很久也没找到讯飞linux下的语音包

**Comment by hgneng** [comment]
讯飞不是自由软件，没有免费下载的正常途径。
