### ISSUE TITLE
声音缺失问题-ekho-7.7.1

### ISSUE THREAD

**Issue by windowxiaoming** [hgneng/ekho#19]
1.按照https://blog.csdn.net/u014470361/article/details/84771720教程安装,至make步骤,未执行make install,运行  ./ekho  "改革春风吹满地 中国人民真争气" -o demo.wav   ,工程目录ekho-7.7.1/下成功生成demo.wav,每个字发音正常.

2.从这个仓库https://sourceforge.net/projects/e-guidedog/files/Ekho-Voice-Data/0.2/下载汉语拼音音频:
a.pinyin-huang-44100-wav-v2.tar.xz
b.pinyin-yali-44100.tar.bz2

3.选取pinyin-yali-44100.tar.bz2包,解压至工程目录ekho-7.7.1/ekho-data/下,并重命名pinyin,pinyin目录下包含各拼音的wav文件

4.删除pinyin.index、pinyin.voice,至工程目录ekho-7.7.1/下, 运行   ./ekho  "改革春风吹满地 中国人民真争气" -o demo1.wav ,生成demo1.wav

demo1.wav里面的“改革春风吹满地”的“风”字没有发音,“中国人民真争气”中只有“民真”两个字发音了,我想程序是没问题的,咨询一下是哪里操作错了.在字典里加入zh_list加入词“华为”,生成语音时“为”字还是读成第四声,好像并未检测到加入的词.

**Comment by hgneng** [comment]
我按描述步骤，并没有重新声音缺失问题，请确认有没有遗漏的细节。

改字典的步骤是这样的：在zh_listx里找到华字开头的行，仿照格式加入华为的拼音，保存；删除zh.dict文件；重新运行就可以按新的拼音来读了。

**Comment by windowxiaoming** [comment]
> 我按描述步骤，并没有重新声音缺失问题，请确认有没有遗漏的细节。
> 
> 改字典的步骤是这样的：在zh_listx里找到华字开头的行，仿照格式加入华为的拼音，保存；删除zh.dict文件；重新运行就可以按新的拼音来读了。

好的,谢谢楼主回复.我再试下

**Comment by windowxiaoming** [comment]
@hgneng  经过尝试,加入词语被检测到了,非常感谢楼主
