### ISSUE TITLE
有关huihui声音文件下载

### ISSUE THREAD

**Issue by yongxiangzheng** [hgneng/ekho#21]
windows版本 程序选择声音有微软huihui这个声音源。但是看到你的安装包没有对应的huihui，请问这个是放在什么位置，还是这个是微软sdk

**Comment by hgneng** [comment]
Windows版调用SAPI5接口，所列出的声音是系统里所有实现了SAPI5接口的声音，包含了非Ekho的声音。huihui不是Ekho的。
