### ISSUE TITLE
/ Ekho-Voice-Data / 0.2下载的pinyin yali文件有问题

### ISSUE THREAD

**Issue by yongxiangzheng** [hgneng/ekho#22]
1、在/ Ekho-Voice-Data / 0.2下载了pinyin yali 1600 4100替换后对于"，"（逗号）不会停顿，并且"，"后面的第一个字会发音很快速，有点跟第二个重叠。
2、后来从windows安装包拷贝pinyin下文件（gsm格式）就不会存在第一点的问题
3、还有生成的声音文件（wav），读最后一个字时候，很快速就没了，这个是否可以设置呢

**Comment by yongxiangzheng** [comment]
补充：是在Ubuntu系统测试

**Comment by hgneng** [comment]
请提供测试的Ekho版本号，请提供一句重现问题的例句。

逗号不停顿的问题在不替换语音文件前是不是不存在？

关于最后一个字很快就没了的问题，也是请提供重现问题的版本和例句。

**Comment by yongxiangzheng** [comment]
版本号：ekho-7.7.1
例子:你好，郑勇祥
我下载的里面拼音资源是pinyin-huang，这个是不存在逗号不停顿问题
最后一个字没了，版本与例子一样

**Comment by hgneng** [comment]
很遗憾，我这边没有重现问题。
