### ISSUE TITLE
g++ 命令 转为 CMakeList的形式怎么写呢？

### ISSUE THREAD

**Issue by linzdg** [hgneng/ekho#23]
g++ 命令 ﻿\  g++ try.cpp libekho.a -pthread  -I. -Iutfcpp/source -Isonic -lsndfile  `pkg-config --libs libpulse-simple` `pkg-config --cflags libpulse-simple`转为 CMakeList的形式怎么写呢？

**Comment by hgneng** [comment]
抱歉，我不会写。
