### ISSUE TITLE
推荐作者添给这个项目加些标签，添加了标签的项目很容易被搜索到

### ISSUE THREAD

**Issue by tangdou1** [hgneng/ekho#26]
比如 TTS， text-to-speech之类的。

**Comment by hgneng** [comment]
请问项目标签在哪里添加？我找不到呢

**Comment by tangdou1** [comment]
> 
> 
> 请问项目标签在哪里添加？我找不到呢
Code 标签下的managetopics
例如这个分叉：
https://github.com/tangdou1/ekho

**Comment by hgneng** [comment]
谢谢，已添加。
