### ISSUE TITLE
Howto choose english voice ?

### ISSUE THREAD

**Issue by lowy** [hgneng/ekho#27]
默认的男声实在是...... 下载的源码里好像是有mbrola 但是不知道怎样设置

**Comment by hgneng** [comment]
英语使用的是eSpeak接口，改声音需要在代码里修改，目前不提供设置。

以前的英语用Festival，声音源会丰富一些，不过没有eSpeak稳定。

eSpeak的声音虽然不太好听，但性能和清晰度优于Festival，对于读屏软件来说可能更佳。

**Comment by lowy** [comment]
感谢作者大大回复 希望你的作品能够帮助到有需要的人们
