### ISSUE TITLE
For Windows Platform找不到"stdafx.h"

### ISSUE THREAD

**Issue by Wence-May** [hgneng/ekho#30]
嗨，您好！
我正在windows平台上使用Ekho的API。但是我发现https://www.eguidedog.net/doc/doc_programme_with_ekho.php 页面的示例中，引用的“stdafx.h"文件在本项目master分支下src/目录下为空。
我不太确定我是否找对了位置，master/src/stdafx.h就是示例中被调用的那个stdafx.h吗?
或者说是不是代码版本或分支的问题呢？

**Comment by Wence-May** [comment]
In addition: I found another 3 "stdafx.h" files in different paths. 
They are:

1. ekho/sapi5/stdafx.h
2. ekho/sapi5/MKVoice/stdafx.h
3. ekho/sapi5/TestSapi5/stdafx.h

Codes in 1&2 are same, but their corresponding "stdafx.cpp" files differ.

So I wonder which one is exactly to be included. I guess the right one may be 1 or 2, but I'm quite a newbee to C++. 
Could anyone help me? 
A lot of thank!!

**Comment by hgneng** [comment]
use ekho/sapi5/stdafx.h

The file should be from Microsoft's library required by Visual Studio. Linux doesn't need it, so the version in src/stdafx.h is empty.

I am afraid that I haven't maintain Windows version for a long time. I am not sure whether you can successfully build ekho from source. But you should be able to build and run the SAPI5 client.
