### ISSUE TITLE
怎么样设置可以在 foliate中使用?

### ISSUE THREAD

**Issue by fratcn** [hgneng/ekho#35]
怎么样在[foliate](https://github.com/johnfactotum/foliate)使用？
根据foliate使用[gtts](https://github.com/johnfactotum/foliate/wiki#how-to-use-text-to-speech)方法修改成ekho:
`#!/bin/bash`
`ekho -s36 --file '-' | play -t mp3 - &`
`trap 'kill $!; exit 0' INT`
`wait`
不能像espeak-ng一样正常顺序朗读，ekho只能捡一两个字快速跳读。

**Comment by hgneng** [comment]
我在Ubuntu20.04上通过snap安装了foliate测试。开始的时候espeak-ng可以朗读。尝试用各种方法设置ekho朗读，一直没有成功听到声音。后来连espeak-ng也没有声音了。我需要花些时间研究一下foliate是怎么用的。

**Comment by fratcn** [comment]
espeak和gtts都可以正常朗读。
不过gtts不能重复运行，多次朗读就会无效，系统重启后才可以，可能是进程退不出来吧，但是进程查询已经没有运行了。也可能是gtts翻墙的缘故。

**Comment by hgneng** [comment]
eSpeak NG声音需要设置成如下命令才能读出测试的中文句子（读成Chinese letter letter...）：`espeak-ng -v mb-en1`

如果重置成不带任何参数的`espeak-ng`则是读不出声音的。

**Comment by hgneng** [comment]
我在文字转语音配置中选择“其它“，填`espeak-ng -v en`可以发声。

如果在本地安装espeak-ng（在安装前foliate已经可以使用espeak-ng，估计foliate内置了一个版本），并做一个espeak-ng2的符号链接，然后在语音设置的“其它“里填`espeak-ng2 -v en`并不能发声。由此猜测eSpeak NG和Festival在foliate里是做过特殊处理的，并非配合命令行的管道操作就能简单实现。

下一步研究一下gtts脚本方式。

**Comment by hgneng** [comment]
另外，我并没有成功使用Festival发声。不知道是怎么配置的。

**Comment by hgneng** [comment]
我知道上面两个comment的原因了。我通过snap安装的版本是在一个类似chroot的环境里的，不能访问当前系统的文件。因此，我在系统里安装的espeak-ng和festival，在snap环境里是调用不了的。

我把snap版本卸载，通过Ubuntu的PPA源重新安装foliate，一切都正常了。

在文字转语音配置的“其它”里填上"ekho -f '-'"就可以读出中文了，不需要gtts脚本的方式。如果不行，请提供epub文件我试试重现问题。

请fratcn试一下，谢谢！

**Comment by hgneng** [comment]
补充说明一下：Ekho默认输出格式是wav，这里play -t mp3可能有点问题。Ekho本身可以播放，不需要管道输出到play命令播放。我觉得声音乱了有可能和这里有关。
`ekho -s36 --file '-' | play -t mp3 - &`

**Comment by fratcn** [comment]
在测试配置里可以朗读，在正常epub阅读中工作不了

**Comment by hgneng** [comment]
我重现问题了。

**Comment by hgneng** [comment]
问题已修复，请下载8.4试试：
https://sourceforge.net/projects/e-guidedog/files/Ekho/8.4/ekho-8.4.tar.xz/download

**Comment by fratcn** [comment]
在archlinux编译下有点麻烦，缺依赖文件estools。archlinux没有对应的ubuntu里libestools-dev包，找到了estools的原github地址https://github.com/festvox/speech_tools/，安装编译也没有成功。

**Comment by hgneng** [comment]
如果没有configure --enable-festival，应该是不需要依赖estools的呀，默认的英语朗读引擎是eSpeak-ng，你想换成Festival？

**Comment by fratcn** [comment]
之前借用了aur上的pkgbuild文件，默认带--enable-festival参数编译。aur上的旧版本好像没人更新维护了。
去掉--enable-festival后编译安装正常通过。
ekho -f '-'朗读正常。
另一个问题，声音有严重的不同步延迟回声，好像同时有两个人在抢着说话，不认真听不清，是参数设置问题吗？

**Comment by hgneng** [comment]
>另一个问题，安装后的默认女声有严重的不同步延迟回声，好像同时有两个人在抢着说话，不认真听不清，是参数设置问题吗？

我没有遇到过这样的问题，会不会是硬件性能不足？

>试着替换voice包，可是哪个目录是拼音的voice目录：

创建pinyin目录，删掉pinyin.voice和pinyin.index。参考：[Ekho主页](http://eguidedog.net/ekho.php) 里有个链接：  [怎样替换Ekho的语音文件](https://cto.eguidedog.net/node/809)

**Comment by fratcn** [comment]
按说明创建pinyin目录，删掉pinyin.voice和pinyin.index。
运行ekho报告：
segmentation fault (core dumped)

**Comment by fratcn** [comment]
创建pinyin目录，删掉pinyin.voice和pinyin.index。正常。
我把44100质量和16000质量都试了一遍，都存在同样的延迟回声问题。输出错误信息如下，是PulseAudio的原因？
终端命令：ekho -f xxx.txt
```
pa_simple_new() failed: Connection refused
pa_sample_spec(format=3,rate=16000,channels=ch=1)
Fail to init audio stream.
Fail to init sound.

```

**Comment by fratcn** [comment]
创建pinyin目录，删掉pinyin.voice和pinyin.index。如常。

试了两种wav质量，44khz和8khz，声音延迟回声依旧。

**Comment by hgneng** [comment]
能否提供一个典型的有声音延迟回声的样本文件？

-o参数可把声音输出到文件。

**Comment by fratcn** [comment]
[音频链接](https://github.com/fratcn/fratcn.github.io/blob/master/images/ekho.wav)

**Comment by hgneng** [comment]
我听了一下样本，符合预期。你在Ekho主页听到的效果应该也是类似。为了减少字间停顿，两个字之间的波形是有些交叠的。效果确实不太理想，但目前技术只能做成这样。抱歉。
