### ISSUE TITLE
请问官网上 显示音标 的功能是如何实现的？

### ISSUE THREAD

**Issue by hezhizheng** [hgneng/ekho#36]
![free-pic](https://static01.imgkr.com/temp/411415b4f5014eefbcaf60dfe10bb5f9.png)

还有，网站上的朗读跟显示音标 这两个功能 一直是 nginx 502 ......

**Comment by hgneng** [comment]
命令行运行`./ekho -l 文本`可以显示拼音（音标）。

服务器磁盘满了，已修复，谢谢反馈！
