### ISSUE TITLE
Android版可否按主页所讲添加语音的方式进行更新语音？

### ISSUE THREAD

**Issue by lgq-lzw** [hgneng/ekho#39]
Android版Ekho可否按ekho主页所讲添加语音方式，将语音包替换掉app生成的原ekho-data目录对应内容以此实现？现在的手机都不在乎那一两百M空间了。

但是几千个零碎小文件拉到手机里是非常耗时的。能否更改一下语音包的文件组成方式？

Android版的好久没更新版本了。

**Comment by hgneng** [comment]
Android版理论上也可以通过类似方式替换语音。

我印象中Android版已经实现了把小文件合并成一个大文件的功能，Linux版第一次运行就会把小文件合并成大文件的缓存文件，小文件从此就不需要了，该大文件放在Android里应该可以用。

考虑到Android里有很多优质免费的TTS，我不打算维护了，好像没什么意义。

**Comment by lgq-lzw** [comment]
我没有linux系统，没法弄出那个大文件。
建议时间精力允许的话，继续维护。Ekho可以实现自定义录制语音及自定义文字词汇拼音的效果是目前其它tts无法比拟的。例如粤语当中的南番顺口音，目前只能通过Ekho实现tts。
即使考虑到其它方面，其实也没多少免费的TTS能实现中文，尤其粤语。
不考虑音质统统使用的话，支持Android9及更高版本的非重复引擎，目前离线式的只有“Ekho TTS Cantonese”、“eSpeak NG”、“Google 文字转语音”、“SmartVoice”、“SVOX Classic TTS”、“讯飞语记”，在线式的只有“大声朗读”(微软Edge TTS引擎)。三星手机系统多一个“三星文字转语音”也有粤语，但不支持其它系统。

**Comment by hgneng** [comment]
在方言的实现上，Ekho确实有其实现简易的优点。但是很少有人愿意贡献语音出来，如果是个人自己私下用，那对传承相关方言的作用比较小。Ekho在Linux平台上的版本维护得最好的，如果有一种新的方言需要支持，那么应该先在Linux上实现。其它平台上要实现方言，没有我的协助是很困难的。而如果我没有相关方言的字典和语音文件，我也帮不上忙。

一年多前，由于我的App内包含了指向我自己网站的外链，违反了Google Play的规定，我的开发账号已经被永久封号（并且警告我不要申请新账号，Google会发现并再次封号），我已无法在Google Play上发布更新。因此，我不太方便维护Android版了。

**Comment by lgq-lzw** [comment]
实测过，Android版不支持直接添加语音文件的方式，无法识别。

我现在以ekho粤语的apk为底板，解包后，用“sourceforge.net/projects/e-guidedog/files/Ekho”这里最新版本ekho(非Android)分支里头的文件中提取的《jyutping.index》《jyutping.voice》《zhy.dict》替换掉Android版对应的《jyutping_index》《jyutping_voice》《zhy.dict》，再打包签名更新安装，以此达到升级效果。尽管我听不出前后版本有什么分别。但新版3个文件体积较旧版要大，估计有提升吧。

只能替换apk里的才有效，不能简单替换掉手机存储根目录里的ekho文件夹当中的对应文件——会被ekho自动换回apk包里的文件。

我用的apk底版是您几年前用邮箱发给我的，我当时用邮箱向您反馈过一些bug。版本号是3.5build8，比ekho网站公开的版本要高。

Google封了也没所谓，大把渠道可用。建议继续开发维护。
没必要局限于eguidedog之类导盲项目，社会上目前调用tts的，多数是报号系统——医院、税务、工商、银行营业厅、车站、公交等，或者是摊贩叫卖。

**Comment by lgq-lzw** [comment]
ekho的Android版还有可提升的地方

部分地方没有对应中文。反编译查过，在《arrays.xml》、《strings.xml》里有定义。不晓得为何个别词条没正常显示。

语音文件应向其它平台版本看齐，可以通用语音文件，且能自动识别——但不要采用大量小文件方式，手机性能撑不住。

语音文件路径不要写死在内置存储根目录固定文件夹，应该可以由用户自定义。不但支持内置存储，SD卡也应支持。高德地图的语音和地图资源就可以自定义到SD卡上。
同样是Android上的tts工具，SmartVoice(采用Vocalizer语音库)甚至支持定义到各个固件分区(例如我就指向了cust分区)，只要用户root了的话。

![Screenshot_2021-02-05-10-57-28-341_com android settings](https://user-images.githubusercontent.com/59247842/106984623-ec321480-67a2-11eb-8db9-c1c2d58cd312.png)

![Screenshot_2021-02-05-10-59-29-265_net eguidedog ekho cantonese](https://user-images.githubusercontent.com/59247842/106984674-fce28a80-67a2-11eb-84f1-09e9a83e8df5.png)

![Screenshot_2021-02-05-10-59-38-157_net eguidedog ekho cantonese](https://user-images.githubusercontent.com/59247842/106984698-0966e300-67a3-11eb-8b01-55440634b253.png)

还是有非中文条目。

![Screenshot_2021-02-05-10-58-11-340_tts smartvoice](https://user-images.githubusercontent.com/59247842/106984738-1a175900-67a3-11eb-8ef7-e02c227e0ec7.png)
考虑一下这种自定义路径的方式，方便内置存储空间紧张的用户。

**Comment by hgneng** [comment]
>没必要局限于eguidedog之类导盲项目，社会上目前调用tts的，多数是报号系统——医院、税务、工商、银行营业厅、车站、公交等，或者是摊贩叫卖。

公共服务的TTS应该不使用Android版本。我觉得如果Ekho TTS的Android版，除非是支持Google 文字转语音和讯飞语记不支持的方言，否则没有存在的必要。

**Comment by watersoft123** [comment]
安卓版安装时提示为旧版，可能无法使用，建议更新下。不过我发现了webspeech，似乎不更新也可以，现在就想着如何把语音放到本地使用

> 在方言的实现上，Ekho确实有其实现简易的优点。但是很少有人愿意贡献语音出来，如果是个人自己私下用，那对传承相关方言的作用比较小。Ekho在Linux平台上的版本维护得最好的，如果有一种新的方言需要支持，那么应该先在Linux上实现。其它平台上要实现方言，没有我的协助是很困难的。而如果我没有相关方言的字典和语音文件，我也帮不上忙。
> 
> 一年多前，由于我的App内包含了指向我自己网站的外链，违反了Google Play的规定，我的开发账号已经被永久封号（并且警告我不要申请新账号，Google会发现并再次封号），我已无法在Google Play上发布更新。因此，我不太方便维护Android版了。

安卓版安装时提示为旧版，可能无法使用，建议更新下。不过我发现了webspeech，似乎不更新也可以，现在就想着如何把语音放到本地使用

**Comment by hgneng** [comment]
我不太明白你的应用场景呢，你应该是可以用讯飞语音的吧？为什么要用Ekho？你也也不应该用WebSpeech，在Android上离线使用WebSpeech会很复杂，也没有什么特别的好处。

**Comment by MrZhangX** [comment]
为啥你打的包不包含中文，只有粤语呢

**Comment by hgneng** [comment]
因为我认为普通话TTS有很多更好的选择，我没有必要维护。
