### ISSUE TITLE
Android app source?

### ISSUE THREAD

**Issue by n8fr8** [hgneng/ekho#4]
This is an amazing project, and I would love to experiment with it more on Android. Is that source available?

**Comment by hgneng** [comment]
I have not moved android source code from SourceForge to github. It's a bit hard to build the Android source code. Many things need to be setup. And I have not touch the code for quite a long time. You can checkout code from here: https://sourceforge.net/p/e-guidedog/code/HEAD/tree/eGuideDog_TTS/

**Comment by kmcheung12** [comment]
@hgneng May I try to help?

**Comment by hgneng** [comment]
@kmcheung12 
Yes, unless maintaining Android version helps yourself too because I don't know how useful the Android version for people. iflytek has a better and free Mandarin TTS for Android.

**Comment by hgneng** [comment]
Nope. I haven't maintain Android version for years.

**Comment by rexpan** [comment]
> @kmcheung12 Yes, unless maintaining Android version helps yourself too because I don't know how useful the Android version for people. iflytek has a better and free Mandarin TTS for Android.

Ekho is the only TTS engine I found for Cantonese.
Currently it still work fine with Android 12 with sometime crash and need to purge all the memory to restart the TTS.

**Comment by rexpan** [comment]
I have tried the Google TTS.
But unfortunately when I use with Google Play Book, it keep using the Mandarin voice instead of hard configured Cantonese voice.

https://user-images.githubusercontent.com/313189/174928320-2904bbf7-775f-45d0-9d9e-55b3619f3c76.mp4

**Comment by hgneng** [comment]
Thank you for reporting. I am convinced that there is value to maintain Ekho Cantonese TTS App again. I will try to update the code to release a new package. Maybe I will also try to record a better voice in the new few months.

**Comment by hgneng** [comment]
Cantonese TTS is now available on Google Play: https://play.google.com/store/apps/details?id=cameronhuang150.ekho

APK can be download at https://sourceforge.net/projects/e-guidedog/files/Ekho/8.7/ekho-cantonese-8.7.apk

Source code is at https://github.com/hgneng/ekho-android-cantonese

Thank you for patience.
