### ISSUE TITLE
「中华古籍」与 ekho 的语引品质

### ISSUE THREAD

**Issue by sati-bodhi** [hgneng/ekho#49]
请问「[中华古籍](http://eguidedog.net/books.php)」语音用的也是 `ekho` 引擎吗？
语音效果相差挺大的。
ekho 的语音会飘来飘去…

**Comment by hgneng** [comment]
不是，中华古籍用的是第三方引擎。

**Comment by sati-bodhi** [comment]
请问那个引擎也是开源的吗？

**Comment by hgneng** [comment]
不是开源的
