### ISSUE TITLE
您好，请问ekho在生成.wav文件时，如何指定采样频率和声道数啊？发现默认是16000Hz, 单声道 ekho-6.3.2

### ISSUE THREAD

**Issue by ai-zml** [hgneng/ekho#52]

**Comment by ai-zml** [comment]
在命令行，似乎也不能指定

**Comment by hgneng** [comment]
不能指定的，音频数据用的频率是什么就是什么，总是单声道的。如果你想改，生成之后用sox转换吧。

**Comment by ai-zml** [comment]
好的，谢谢。似乎Windows平台似乎支持，运行exe文件，有一个下拉列表可供选择不同的采样频率和声道数。
我是交叉编译了源码，往arm-linux上移植，发现不能指定这两个参数。如果我想修改源码以支持修改两个参数，
请问容易实现吗？可以指点一二吗？非常感谢 :D

**Comment by hgneng** [comment]
Windows是SAPI5接口做的支持，不是Ekho本身做的。由于目前录制的音频都是单声道的，支持双声道感觉没什么意义。修改输出采样率的话应该不是很难。你是想在命令行里调用，还是C++里调用的？

**Comment by ai-zml** [comment]
真的非常谢谢你的回答。我是想在C++里调用。
我有一个简单的想法，我想在Ekho输出数据的pipeline上，移植部分sox的功能，将Ekho输出的单声道和固定采样率的数据，转换为双声道和可变采样率的数据，不知道这是否可行？

**Comment by hgneng** [comment]
我这几天研究一下，应该不需要pipeline。

**Comment by hgneng** [comment]
实现了，请pull一下最新代码来用。

命令行用法如下：
./ekho 123 --samplerate 8000 --channel 2 -o demo.wav

C++用法如下（注意先设置samplerate和channel，再设置语言）：
` 
  Ekho *ekho = new Ekho();
  ekho->setSampleRate(8000);
  ekho->setChannels(2);
  ekho->setVoice("Mandarin");
  int pcmSize;
  short *pcm = ekho->synth3("123", pcmSize);
`
