### ISSUE TITLE
CentOS 7  -lespeak-ng... no

### ISSUE THREAD

**Issue by laoqin2601** [hgneng/ekho#55]
```
checking for main in -lsndfile... yes
checking for main in -lespeak-ng... no
configure: error: in `/root/ekho-8.6':
configure: error: espeak-ng test failed
```

```
CentOS 7
ekho-8.6
```

yum提示没有`devtoolset-4-gcc*`，安装了`devtoolset-7-gcc*`
`espeak-devel`也安装了
有CentOS7下的安装参考吗，6有点老了。

**Comment by hgneng** [comment]
espeak-ng和espeak不是同一个包，它是espeak原作者没有维护后，由别的人另外再接着开发的。在新一些的Linux中会同时存在espeak和espeak-ng。如果Linux发行版没有espeak-ng包，你需要自行从源码编译安装：https://github.com/espeak-ng/espeak-ng
