### ISSUE TITLE
WebSpeech如何将语音文件放到本地？

### ISSUE THREAD

**Issue by watersoft123** [hgneng/ekho#57]
我在主页面板上发现了用js实现的tts，在js文件里面看到可以使用localhost，我想它可能支持本地语音，我想把语音文件放到本地使用，想问如何下载webspeech使用的语音文件？在页面的例子中，我看到可以选择百度，讯飞等其它语音，如果我有这些引擎的语音包，是否可以在webspeech中使用，如何在本地放置这些语音文件？

**Comment by hgneng** [comment]
参考这个文档搭建自己的语音服务器：https://eguidedog.net/doc/doc_setup_espeak_server.php

把里面espeak的命令替换成生成讯飞或百度语音文件的命令。

**Comment by watersoft123** [comment]
> 参考这个文档搭建自己的语音服务器：https://eguidedog.net/doc/doc_setup_espeak_server.php
> 
> 把里面espeak的命令替换成生成讯飞或百度语音文件的命令。

谢谢你这么快回复我的问题，可能你误解了我的意图。我这个是要用在移动设备上，比如安卓或苹果手机，我不想把语音文件放到服务器上，我想放在手机上以便离线使用。如果必须要通过一个url，那么我可以在手机上建立一个http本地服务器，和手机内的语音文件建立联系。比如此前我用abcjs制作五线谱，播放时需要调用soundfont，我把远程soundfont下载后放在手机上，然后通过http本地服务器进行访问。

**Comment by hgneng** [comment]
我写过一个叫《古籍库》的Android应用：https://eguidedog.net/books.php 。里面有朗读功能，可以通过WebSpeech联网调用服务器的语音，也可以离线调用本地的语音引擎。

调用本地语音引擎的话主要是研究系统TTS的接口，和WebSpeech可以没什么关系，再搞个HTTP服务感觉有点复杂了。如果是基于Web技术的App，可以用Java写一些供JS调用的接口，由Java去调用系统TTS接口。

**Comment by watersoft123** [comment]
> 我写过一个叫《古籍库》的Android应用：https://eguidedog.net/books.php 。里面有朗读功能，可以通过WebSpeech联网调用服务器的语音，也可以离线调用本地的语音引擎。
> 
> 调用本地语音引擎的话主要是研究系统TTS的接口，和WebSpeech可以没什么关系，再搞个HTTP服务感觉有点复杂了。如果是基于Web技术的App，可以用Java写一些供JS调用的接口，由Java去调用系统TTS接口。

谢谢，我现在是在使用系统TTS离线语音，但总觉得比较麻烦，有的手机没装语音引擎，还要提醒装一个。另外没有暂停功能，只能先转为音频文件，再用播放器实现暂停功能。字符串长度也有限制。webspeech.js可以整合到自己的app中，且有暂停功能，长度是否有限制我没测试，只是目前离线似乎有点麻烦，能够在移动设备上离线使用就更好了。

**Comment by watersoft123** [comment]
> 我写过一个叫《古籍库》的Android应用：https://eguidedog.net/books.php 。里面有朗读功能，可以通过WebSpeech联网调用服务器的语音，也可以离线调用本地的语音引擎。
> 
> 调用本地语音引擎的话主要是研究系统TTS的接口，和WebSpeech可以没什么关系，再搞个HTTP服务感觉有点复杂了。如果是基于Web技术的App，可以用Java写一些供JS调用的接口，由Java去调用系统TTS接口。

找到一个espeak引擎的的纯js版，能支持普通话和粤语，但似乎得先转换成拼音才能读，而且声音效果不是太理想，不知道能不能和webspeech结合起来，采用echo的语音文件离线播放。
https://www.masswerk.at/mespeak/

**Comment by hgneng** [comment]
没想到有人把eSpeak移植到JS上，真是长见识了。我不知道怎样能让eSpeak用Ekho的语音文件来读呢。

**Comment by watersoft123** [comment]
> 没想到有人把eSpeak移植到JS上，真是长见识了。我不知道怎样能让eSpeak用Ekho的语音文件来读呢。

那我更不知道了，也许用拼音对应wav音库。不过我有个疑问，Ekho的音库采用的是wav，为何不采用体积更小的mp3？我用过github上的paul的ABCjs库，这个是制作五线谱的js，播放音符的soundfont，采用的是录制好的一个个mp3单音符文件与一个个音符相对应。声音跟真正的乐器肯定有差别，但听起来也相当不错，也很流畅。
https://github.com/paulrosen/abcjs

**Comment by hgneng** [comment]
我一直觉得五线谱很难画，我自己连规则都搞不清楚，不知道什么情况下该把哪些符尾连起来。也写过基于JS的播放五线谱的应用，不过节奏快了就卡，感觉专业的音乐应用不能用JS写。

Ekho支持MP3格式的，源代码的scripts里应该有一个批量把整个目录转为WAV的脚本。

**Comment by watersoft123** [comment]
> 我一直觉得五线谱很难画，我自己连规则都搞不清楚，不知道什么情况下该把哪些符尾连起来。也写过基于JS的播放五线谱的应用，不过节奏快了就卡，感觉专业的音乐应用不能用JS写。
> 
> Ekho支持MP3格式的，源代码的scripts里应该有一个批量把整个目录转为WAV的脚本。

谢谢，我的目的其实就是想在webspeech里面离线使用这些MP3音源，不要通过服务器端，但这个可能与你的想法背道而驰，因此实施有难度，暂且打消了这个念头。
