### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by linsui** [hgneng/ekho#58]
请问 Android 应用是否开源？可以将 Android 应用发布到 F-Droid 吗？谢谢！

**Comment by hgneng** [comment]
Android应用开源，可以发布到F-Droid。不过我多年没有维护了。代码需要到这里去找：
https://sourceforge.net/p/e-guidedog/code/HEAD/tree/eGuideDog_TTS/

**Comment by linsui** [comment]
确实好几年没有更新了，我不确定我能不能成功打包，我会尝试一下，谢谢！

**Comment by linsui** [comment]
这个代码使用的 ant 现在 F-Droid 已经放弃支持了。恐怕需要更新一下迁移到 gradle 才能构建。抱歉。
