### ISSUE TITLE
how to use ekho in qt5(ubuntu) like a library?

### ISSUE THREAD

**Issue by daxianghrh** [hgneng/ekho#59]
相机拍到一张有文字的图片，经识别后语音播放出来。请问如何在qt下移植ekho实现此功能?

**Comment by hgneng** [comment]
语音识别部分需要另找软件实现。

语音合成的话，你可以用启用shell进程方式调用ekho命令；也可以连接ekho的C++库，参考src/test_ekho.cpp。
