### ISSUE TITLE
Building error

### ISSUE THREAD

**Issue by halida** [hgneng/ekho#6]
after running `autoreconf --install; ./configure`

Run make:

```
 $ make
make  all-am
make[1]: Entering directory '/home/halida/data/workspace/source/ekho'
make[1]: *** No rule to make target '../libmusicxml/libmusicxml2.a', needed by 'test_ekho'.  Stop.
make[1]: Leaving directory '/home/halida/data/workspace/source/ekho'
Makefile:456: recipe for target 'all' failed
make: *** [all] Error 2
```

How to solve that? Thanks.

Also could you update the INSTALL file about it? Thanks.

**Comment by hgneng** [comment]
I've updated Makefile.am to include rule to make libmusicxml2.a. Please update and have a try.

**Comment by halida** [comment]
@hgneng Thanks, It works now.
