### ISSUE TITLE
是否有可能只通过一个声调的音源构造出其他声音？

### ISSUE THREAD

**Issue by ShizuhaAki** [hgneng/ekho#63]
这是一个技术问题。

假设出于某种原因，我只能获取到某一个声调（不妨假定为 1）的声音，从技术上讲，是否可能通过它构造出其他声调？

如果可以的话，那么为歌声合成软件所准备的音源（例如 UTAU）就可以在 ekho 中使用。

**Comment by hgneng** [comment]
我曾经用praat做过这件事。先从已有的声音文件中分析出不同声调的轮廓，然后把这个轮廓应用到新的声音，大致是可以生成不同声调的。

不过，由于最终效果不及真人录制，我没有推进研发，已做的工作也不知道放哪里了。

至于歌声合成，我也是尝试做过的，但是效果惨不忍睹。这个和改变声调不完全相同。歌声中一个字的基频（pitch）应该是比较稳定的，而声调的基频其实是发生变化的。目前的pitch是可以调整的，但是我想，可能这个值的计算不是很准，调整到目标pitch的算法也不是很准确，最终导致出来的效果很差。

有一个叫“酷狗唱唱”的K歌软件，里面有个一键修音的功能，修音后评分会更高，但我个人觉得听起来更难听。

这种技术还是需要做很多研究，对每一个细节都做得很好才能有比较好的效果。也许可以从深度学习方向突破。我不太懂。
