### ISSUE TITLE
github上, 没有visual studio的工程, 官网的教程中显示有

### ISSUE THREAD

**Issue by HZH35789** [hgneng/ekho#64]

**Comment by hgneng** [comment]
为了遵从Debian的一些规范，在这次提交中移除了：
https://github.com/hgneng/ekho/commit/f35d4ddadf3a18713ff211f2d6db1f0aa1547f92

当时应该移到一个新的repo里的。

你可以在这个地方下载，在sapi5目录：
https://github.com/hgneng/ekho/releases/tag/v8.9.3

**Comment by HZH35789** [comment]
多谢!
