### ISSUE TITLE
build ekho-9.0.tar.xz "fatal error: utf8.h: No such file or directory"

### ISSUE THREAD

**Issue by Kay-Anonymous** [hgneng/ekho#69]
Hello, gurus.
I want to build ekho-9.0 in Raspberry Pi 4B. I built ekho-8.6 on this device a few months ago.

I'm download ekho-9.0.tar.xz  form http://www.eguidedog.net/ekho.php.
And then run ./configure successed!

but i get this error when "make":
```
make: *** [Makefile:674: src/libekho_a-libekho_impl.o] Error 1
make: *** [Makefile:660: src/libekho_a-libekho.o] Error 1
make: *** [Makefile:786: src/libekho_a-musicxml.o] Error 1
In file included from ../src/ekho_dict.h:29,
                 from ../src/phonetic_symbol.cpp:27:
../src/character.h:28:10: fatal error: utf8.h: No such file or directory
   28 | #include "utf8.h"
      |          ^~~~~~~~
compilation terminated.
```

utf8.h is here
```
# find /usr/include/ -name utf8.h
/usr/include/pulse/utf8.h
```

I don't know how to fix it. Could you help me?

**Comment by hgneng** [comment]
Try to install this lib: libutfcpp-dev (https://utfcpp.sourceforge.net/)

I didn't check this lib in configure because it doesn't exists in MacOSX.

**Comment by Kay-Anonymous** [comment]
Thanks, it's work will right now~
