### ISSUE TITLE
9.0 version missing utf8.h file

### ISSUE THREAD

**Issue by xuniuer** [hgneng/ekho#71]
Hi there,

When I try to compile the latest version in wsl environment, after `./configure` successfully, but `make` complains 
```
g++ -DHAVE_CONFIG_H -I.    -Wall -DEKHO_DATA_PATH='"/usr/local/share/ekho-data"' -g  -g -O2 -MT src/test_ekho-test_ekho.o -MD -MP -MF src/.deps/test_ekho-test_ekho.Tpo -c -o src/test_ekho-test_ekho.o `test -f 'src/test_ekho.cpp' || echo './'`src/test_ekho.cpp
In file included from src/ekho_dict.h:29,
                 from src/ekho.h:49,
                 from src/test_ekho.cpp:29:
src/character.h:28:10: fatal error: utf8.h: No such file or directory
   28 | #include "utf8.h"
      |          ^~~~~~~~
compilation terminated.
```

In the repo, there is no `utf8.h` included.

**Comment by xuniuer** [comment]
Fixed by: 
`sudo apt install libutfcpp-dev`

Plus, in phrase of `./configure`, another two libraries needs to install
```
libsonic-dev
libespeak-ng-dev
```

Above may be helpful to project documents.

**Comment by hgneng** [comment]
Thank you. It is documented in INSTALL file.

**Comment by xuniuer** [comment]
Another possible problem is about server mode. 

If want to make server mode (`ekho --server`) work, `./configure` should add an option `--with-mp3lame`, otherwise the output will fail.
