### ISSUE TITLE
make时，报头文件utf8.h不存在

### ISSUE THREAD

**Issue by wangbintao-wbt** [hgneng/ekho#72]
未查到相关资料，烦请作者能解惑，万分感谢

In file included from src/ekho_dict.h:29,
                 from src/ekho.h:49,
                 from src/test_ekho.cpp:29:
src/character.h:28:10: fatal error: utf8.h: 没有那个文件或目录
   28 | #include "utf8.h"
      |          ^~~~~~~~
compilation terminated.
make: *** [Makefile:855：src/test_ekho-test_ekho.o] 错误 1

**Comment by hgneng** [comment]
你需要这个库：libutfcpp-dev，见INSTALL文件。

**Comment by wangbintao-wbt** [comment]
感谢大佬
