### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by hellozous** [hgneng/ekho#74]
为了安装ekho，我写了个sh文件：EkhoInstall.sh

```
sudo tar -zxvf ekho-9.0.tar.gz
cd ekho-9.0
pwd
sudo apt-get update -y
sudo apt-get install autoconf libtool -y
./autogen.sh
sudo apt-get install libsndfile1-dev libespeak-ng-dev libpulse-dev texinfo libltdl-dev libmpg123-dev libsonic-dev libutfcpp-dev -y
./configure
make CXXFLAGS=-O0
sudo make install
```
直接输入命令运行的话 sh EkhoInstall.sh就没问题
但我在java中用 
`ProcessBuilder processBuilder = new ProcessBuilder("/bin/sh", "-c", "sh EkhoInstall.sh");`
安装之后就报这个错

```
Fail to open file /usr/local/share/ekho-data/zh_list at 901
Fail to load espeak dictionary: /usr/local/share/ekho-data/zh_list
Fail to find voice data directory: /usr/local/share/ekho-data/pinyin
Fail to setVoice of dictionary
Voice sample rate not set. Maybe you have not setVoice first.
Audio::processorStream not init
Segmentation fault
```

请问这个该怎么解决啊？

**Comment by hgneng** [comment]
Java的Shell环境变量可能不同于Bash，导致默认安装路径不同。你可以把sudo make install的输出重定向到文件，看看文件到装到哪个目录了。或者用locate命令找。

./configure --prefix=/usr/local可以指定安装路径前缀。

运行的时候EKHO_DATA_PATH=/usr/local/share/ekho-data ./ekho 123可以指定ekho-data目录的位置。

**Comment by hellozous** [comment]
折腾了3天三夜，终于解决了：

`sudo chmod 755 /usr/local/share/ekho-data/.`
