### ISSUE TITLE
When installing ekho-9.0.tar.xz, error: espeak-ng test failed is reported

### ISSUE THREAD

**Issue by hanyuanzhong** [hgneng/ekho#75]
hi [hgneng](https://github.com/hgneng)

$ sudo apt-get install libsndfile1-dev libpulse-dev libncurses5-dev libmp3lame-dev libespeak-dev
$ tar xJvf ekho-xxx.tar.xz
$ cd ekho-xxx
$ ./configure

When the./configure command is executed in Raspberry Pi, an error message is displayed. configure: error: espeak-ng test failed
See `config.log' for more details
After apt-get install espeak-ng is installed, an error still occurs: configure: error: espeak-ng test failed

**Comment by hgneng** [comment]
You need to install ibespeak-ng-dev. Please check INSTALL file.

**Comment by hanyuanzhong** [comment]
谢谢,我已经安装好了,
我执行了下面这个命令重新安装了,里面有包含您说的libespeak-ng-dev
命令如下:
sudo apt-get install texinfo libltdl-dev libmpg123-dev libsonic-dev libutfcpp-dev libespeak-ng-dev libsndfile1-dev libpulse-dev libncurses5-dev libestools-dev festival-dev libvorbis-dev libmp3lame-dev libdotconf-dev
