### ISSUE TITLE
新版本的Audacity 3.5.1 如何录制自己的声音以及如何提取单个拼音的音频

### ISSUE THREAD

**Issue by hanyuanzhong** [hgneng/ekho#78]
是因为提取的音频不对,导致的替换自己声音不对吗

![image](https://github.com/hgneng/ekho/assets/48727363/d99d5d4d-cbe1-41ce-92b3-dfcd9891b380)
请教一下: 我从   https://eguidedog.net/doc/doc_make_new_voice_cn.php   链接中查看添加新的声音,在官网下载Audacity 3.5.1 软件之后,打开新版本
在Audacity菜单->分析, 在下拉按钮中 没有"声音寻找"
然后我点击分析发现有一个"为声音添加标签"和剩下的材质很像,但是在弹窗里,其他的参数要设置为多少呢:如下图:
![image](https://github.com/hgneng/ekho/assets/48727363/e0cbad31-146a-4371-82f5-90291378691f)
![image](https://github.com/hgneng/ekho/assets/48727363/f7f9ce6b-5253-4a81-b367-3b9a9fc17a42)

**Comment by hanyuanzhong** [comment]
我用老版本Audacity 2.3.2的,按照文档,以及提供的"0-9的音频"提取的单个音频文件可以正常的播放,

**Comment by hgneng** [comment]
我没有用过新版本。我觉得你可以根据自己录制音频波形的特征来设定参数，然后试一下标记，如果没有标错参数就合适。如果标错了就调整一下咯。

**Comment by hanyuanzhong** [comment]
> 我没有用过新版本。我觉得你可以根据自己录制音频波形的特征来设定参数，然后试一下标记，如果没有标错参数就合适了。如果错了就调整一下咯标。

嗯嗯好的,我装成2.3.2版本的了
