### ISSUE TITLE
老师，请教一下啊，新声音现在感觉是一个子一个字读出来的，很生硬，一句话一句话的读，需要连贯性的读，需要配置吗？还是怎么弄得啊

### ISSUE THREAD

**Issue by liunaqq** [hgneng/ekho#79]

**Comment by hgneng** [comment]
没有可配置的地方，Ekho本来就是这个效果。如果你觉得自己制作的声音没有自带的好，可以仔细对比一下自带声音的音频和你自己制作的音频细节，看在录制和切割的阶段有没有可以改进的地方（噪音水平，单字时长，前后空白时长，单字录制声音发音的平稳性）。

**Comment by liunaqq** [comment]
好的，谢谢老师
