### ISSUE TITLE
can make a guid for 潮州话 ?

### ISSUE THREAD

**Issue by limweb** [hgneng/ekho#8]
can make a guid for 潮州话 ?

Thanks.

**Comment by hgneng** [comment]
1. 选择一种潮州话拼音系统，列出所有拼音。
2. 按顺序为每个拼音录制音频，可以保存成一个或多个文件，每个拼音间保留一些空白。
3. 人工（或借助脚本）剪切音频文件，让每个拼音独立一个音频文件。
4. 添加一些代码支持。
如果声音文件以GPL2许可发布，3、4步可直接让我来完成。
参考资料：http://www.eguidedog.net/doc/doc_make_new_voice.php

**Comment by cnscns** [comment]
声音间隔时间能否通过代码短一点，转出来以后感觉间隔偏长了一点

**Comment by cnscns** [comment]
例如读我们，我 和 们之间间隔时间太长

**Comment by hgneng** [comment]
暂没有很好的算法实现。

这个需要在音频剪切的时候波形两边不要留空白。曾经写过一些算法让音量很小的部分交叠，但部分字的音会变得很弱分辨不清，后来基本取消了这种交叠的算法。不过这不代表这个思路不可行，只是我的算法不够好。

当一个词读得比较连贯的时候，它其实不是两个字音频波形的单纯拼接，第一个字的尾音和第二个字的首音会发生一定的变形。

**Comment by cnscns** [comment]
当前有中文语音wav文件，能否帮忙转成ekho能处理的文件，wav文件可以开源出来

**Comment by hgneng** [comment]
有词典吗？语音文件放网盘？或者QQ给我(QQ:122206051)?
