### ISSUE TITLE
请问 windows 安装包中为什么没有 ekho 这个命令行工具，只有一个 ttsapp.exe 这个gui 工具呢

### ISSUE THREAD

**Issue by mei-rune** [hgneng/ekho#84]
请问 windows 安装包中为什么没有 ekho 这个命令行工具，只有一个 ttsapp.exe 这个gui 工具呢

这个 ttsapp.exe 的源码在哪里？

**Comment by mei-rune** [comment]
另外，我想在 windows 上编译，有说明么？

**Comment by hgneng** [comment]
Windows版的VS工程代码在这里：https://github.com/hgneng/ekho-sapi5。调试起来会比较困难，我隔几年才编译一次，通常各种软件都更新了，也不记得当时的步骤，要慢慢调。
Windows实现的是SAPI5接口，没有命令行工具。

**Comment by mei-rune** [comment]
谢谢
