### ISSUE TITLE
make install error in ubuntu16.04

### ISSUE THREAD

**Issue by nature1317** [hgneng/ekho#9]
cd ./libmusicxml/linux && make
make[1]: Entering directory '/home/btows/ekho/libmusicxml/linux'
make -C ../samples
make[2]: Entering directory '/home/btows/ekho/libmusicxml/samples'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/btows/ekho/libmusicxml/samples'
make[1]: Leaving directory '/home/btows/ekho/libmusicxml/linux'
make[1]: Entering directory '/home/btows/ekho'
 /bin/mkdir -p '/usr/local/bin'
  /bin/bash ./libtool   --mode=install /usr/bin/install -c test_ekho ekho '/usr/local/bin'
libtool: install: /usr/bin/install -c test_ekho /usr/local/bin/test_ekho
libtool: install: /usr/bin/install -c ekho /usr/local/bin/ekho
 /bin/mkdir -p '/usr/local/include'
 /usr/bin/install -c -m 644 src/ekho.h src/ekho_dict.h src/character.h src/phonetic_symbol.h src/zhy_symbol_map.h src/zh_symbol_map.h src/ekho_typedef.h src/ekho_impl.h utfcpp/source/utf8.h '/usr/local/include'
make  install-data-hook
make[2]: Entering directory '/home/btows/ekho'
mkdir -p /usr/local/share/ekho-data
cp -RLf ./ekho-data/alphabet ./ekho-data/hakka ./ekho-data/tibetan ./ekho-data/ngangien ./ekho-data/hangul ./ekho-data/toisanese /usr/local/share/ekho-data/
cp: 无法获取'./ekho-data/alphabet' 的文件状态(stat): 没有那个文件或目录
cp: 无法获取'./ekho-data/hakka' 的文件状态(stat): 没有那个文件或目录
cp: 无法获取'./ekho-data/tibetan' 的文件状态(stat): 没有那个文件或目录
cp: 无法获取'./ekho-data/ngangien' 的文件状态(stat): 没有那个文件或目录
cp: 无法获取'./ekho-data/hangul' 的文件状态(stat): 没有那个文件或目录
cp: 无法获取'./ekho-data/toisanese' 的文件状态(stat): 没有那个文件或目录
Makefile:1382: recipe for target 'install-data-hook' failed
make[2]: *** [install-data-hook] Error 1
make[2]: Leaving directory '/home/btows/ekho'
Makefile:1305: recipe for target 'install-data-am' failed
make[1]: *** [install-data-am] Error 2
make[1]: Leaving directory '/home/btows/ekho'
Makefile:1250: recipe for target 'install-am' failed
make: *** [install-am] Error 2

**Comment by hgneng** [comment]
Please copy those missing folders from a distribution package. Those folders contains voice data which is not included in github source code. `touch` an empty file may also work if you don't need those voices.

**Comment by nature1317** [comment]
@hgneng Thanks! One more question，What shall I do if I want to replace pinyin-huang voice with pinyin-yali voice

**Comment by hgneng** [comment]
There is a Chinese document at the bottom of Ekho home page: http://www.eguidedog.net/ekho.php

怎样替换Ekho的语音文件：http://cto.eguidedog.net/node/809

**Comment by nature1317** [comment]
Ok,Thanks
